import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:sons_rodrigo_faro/app/modules/home/submodules/lista_audios/domain/entities/audio.dart';

const bannerID = 'ca-app-pub-1898798427054986/8664455823';
const intersticialID = 'ca-app-pub-1898798427054986/8094390437';

Color randomColor() {
  final colors = [
    Colors.red,
    Colors.blue,
    Colors.green,
    Colors.pink,
    Colors.purple,
    Colors.indigo,
    Colors.lime,
    Colors.orange,
    Colors.teal,
  ];

  return colors[math.Random().nextInt(colors.length)];
}

final List<Audio> listAudios = [
  Audio(
    id: -23,
    name: 'Xiiii',
    filePath: 'audios/xii.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -22,
    name: 'Vai da namoro',
    filePath: 'audios/vaidanamoro.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -21,
    name: 'UIII',
    filePath: 'audios/ui.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -20,
    name: 'Uepaa',
    filePath: 'audios/uepa.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -19,
    name: 'Toomm',
    filePath: 'audios/tomtom.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -18,
    name: 'Risada maluca 4',
    filePath: 'audios/risadamaluca.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -17,
    name: 'Risada maluca 3',
    filePath: 'audios/risada.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -16,
    name: 'Rapaazzz',
    filePath: 'audios/rapaz.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -15,
    name: 'Que isso!',
    filePath: 'audios/queisso.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -14,
    name: 'Pare',
    filePath: 'audios/pare.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -13,
    name: 'Olha ele',
    filePath: 'audios/olhaele.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -12,
    name: 'Ihaaa',
    filePath: 'audios/ihaa.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -11,
    name: 'Risada maluca 2',
    filePath: 'audios/hahah.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -10,
    name: 'Esqueça tudo',
    filePath: 'audios/esquecatudo.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -9,
    name: 'Ele gooosta',
    filePath: 'audios/elegosta.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -8,
    name: 'Demaaais',
    filePath: 'audios/demais.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -7,
    name: 'Dança gatinho',
    filePath: 'audios/danca.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -6,
    name: 'Chega',
    filePath: 'audios/chega.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -5,
    name: 'Risada maluca',
    filePath: 'audios/auhaudha.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -4,
    name: 'Aiai',
    filePath: 'audios/aiai.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -3,
    name: 'Ai',
    filePath: 'audios/ai.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -2,
    name: 'Tomeee',
    filePath: 'audios/tome.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -1,
    name: 'Cavalo',
    filePath: 'audios/cavalo.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
];
